# Helm chart values
controllerConfig:
  # featureGates set of key: value pairs that describe AWS load balance controller features
  featureGates:
    NLBGatewayAPI: true
    ALBGatewayAPI: true
  # ListenerRulesTagging: true
  # WeightedTargetGroups: true
  # ServiceTypeLoadBalancerOnly: false
  # EndpointsFailOpen: true
  # EnableServiceController: true
  # EnableIPTargetType: true
  # SubnetsClusterTagCheck: true
  # NLBHealthCheckAdvancedConfig: true
  # ALBSingleSubnet: false
  # LBCapacityReservation: true
  # GlobalAcceleratorController: false
  # EnhancedDefaultBehavior: false
  # EnableDefaultTagsLowPriority: false
  # ALBTargetControlAgent: false